services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: false
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: false
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: true

  bitrix_orm.object_watcher:
    class: Prokl\BitrixOrmBundle\Base\ObjectWatcher

  bitrix_orm.file_factory:
    class: Prokl\BitrixOrmBundle\Base\Factories\FileFactory
    arguments: ['@bitrix_orm.object_watcher']

  bitrix_orm.file_repository:
    class: Prokl\BitrixOrmBundle\Base\Repository\FileRepository
    arguments: ['@bitrix_orm.file_factory']

  Prokl\BitrixOrmBundle\Registry\RepositoryRegistryInterface:
    class: Prokl\BitrixOrmBundle\Registry\RepositoryRegistry
    public: true
    calls:
      - ['setContainer', ['@service_container']]

  bitrix_orm.repository_registry:
    alias: Prokl\BitrixOrmBundle\Registry\RepositoryRegistryInterface
    public: true
